AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SecretPrefix:
    Type: String
    Default: /rds/user/
Resources:
  SyncUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 60
      Architectures:
        - arm64
      Environment:
        Variables:
          SECRET_PREFIX: !Ref SecretPrefix
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 
                - secretsmanager:CreateSecret
                - secretsmanager:UpdateSecret
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretPrefix}*
            - Effect: Allow
              Action: 
                - secretsmanager:ListSecrets
              Resource: "*"


  ## 作成されるロールを拡張機能を追加するRDSインスタンスに別途手動で紐付ける
  PgsqlUserSyncFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: rds.amazonaws.com
      Policies:
        - PolicyName: "pgsql-user-sync-function-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt SyncUserFunction.Arn
Outputs:
  FunctionArn:
    Value: !GetAtt SyncUserFunction.Arn
